
const userPermissions = {
    LENDER: {
        ONBOARD_LENDER: 'ONBOARD_LENDER',
        EDIT_LENDER: 'EDIT_LENDER',
        VIEW_LENDERS: 'VIEW_LENDERS',
        UPLOAD_LENDER_AGREEMENTS: 'UPLOAD_LENDER_AGREEMENTS',
    },
    LENDER_PRODUCT: {
        ADD_LENDER_PRODUCT: 'ADD_LENDER_PRODUCT',
        EDIT_LENDER_PRODUCT: 'EDIT_LENDER_PRODUCT',
        VIEW_LENDER_PRODUCTS: 'VIEW_LENDER_PRODUCTS',
        UPDATE_LENDER_PRODUCT_STATUS: 'UPDATE_LENDER_PRODUCT_STATUS',
    },
    LENDER_SUPPORT: {
        ADD_LENDER_SUPPORT: 'ADD_LENDER_SUPPORT',
        EDIT_LENDER_SUPPORT: 'EDIT_LENDER_SUPPORT',
        VIEW_LENDER_SUPPORTS: 'VIEW_LENDER_SUPPORTS',
        DELETE_LENDER_SUPPORT: 'DELETE_LENDER_SUPPORT',
    },
    EXECUTIVES: {
        ADD_EXECUTIVE: 'ADD_EXECUTIVE',
        EDIT_EXECUTIVE: 'EDIT_EXECUTIVE',
        VIEW_EXECUTIVES: 'VIEW_EXECUTIVES',
        DELETE_EXECUTIVE: 'DELETE_EXECUTIVE',
    },
    LEADS: {
        ASSIGN_LEADS: 'ASSIGN_LEADS',
        VIEW_LEADS: "VIEW_LEADS",
        VIEW_MANAGE_LEADS: "VIEW_MANAGE_LEADS",
        UPDATE_LEAD_STATUS:"UPDATE_LEAD_STATUS"
    }

};

const employmentTypes = {
    SALARIED: "Salaried",
    SELF_EMPLOYED: "Self Emp",
    RETIRED: "Retired",
    STUDENT: "Student"
}

export {
    userPermissions,
    employmentTypes
}
